import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function RequestsTrendChart({ data }) {
    const maxRequests = Math.max(...data.map((d) => d.requests));
    const maxCompletions = Math.max(...data.map((d) => d.completions));
    const maxValue = Math.max(maxRequests, maxCompletions);
    const dateFormatter = (timestamp) => {
        const date = new Date(timestamp);
        return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    };
    return (_jsxs("div", { className: "space-y-6", children: [_jsx("div", { className: "bg-gray-50 rounded-lg p-4", children: _jsx("div", { className: "flex gap-4 items-end justify-between h-80", children: data.map((item, idx) => {
                        const reqHeight = (item.requests / maxValue) * 100;
                        const compHeight = (item.completions / maxValue) * 100;
                        return (_jsxs("div", { className: "flex-1 flex flex-col items-center gap-2", children: [_jsxs("div", { className: "w-full flex gap-1 items-end justify-center h-64", children: [_jsx("div", { className: "flex-1 bg-blue-400 rounded-t opacity-75 relative group", style: { height: `${reqHeight}%` }, children: _jsx("div", { className: "hidden group-hover:block absolute -top-8 left-1/2 -translate-x-1/2 bg-gray-800 text-white text-xs px-2 py-1 rounded whitespace-nowrap", children: item.requests }) }), _jsx("div", { className: "flex-1 bg-green-400 rounded-t opacity-75 relative group", style: { height: `${compHeight}%` }, children: _jsx("div", { className: "hidden group-hover:block absolute -top-8 left-1/2 -translate-x-1/2 bg-gray-800 text-white text-xs px-2 py-1 rounded whitespace-nowrap", children: item.completions }) })] }), _jsx("p", { className: "text-xs text-gray-600 text-center", children: dateFormatter(item.timestamp) })] }, idx));
                    }) }) }), _jsxs("div", { className: "grid md:grid-cols-2 gap-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-4 h-4 bg-blue-400 rounded" }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-gray-900", children: "Total Requests" }), _jsxs("p", { className: "text-xs text-gray-600", children: ["Avg: ", (data.reduce((sum, d) => sum + d.requests, 0) / data.length).toFixed(0)] })] })] }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-4 h-4 bg-green-400 rounded" }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-gray-900", children: "Completed" }), _jsxs("p", { className: "text-xs text-gray-600", children: ["Avg: ", (data.reduce((sum, d) => sum + d.completions, 0) / data.length).toFixed(0)] })] })] })] }), _jsxs("div", { className: "grid md:grid-cols-3 gap-4 p-4 bg-gray-50 rounded-lg", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-600 uppercase", children: "Peak Requests" }), _jsx("p", { className: "text-2xl font-bold text-gray-900", children: Math.max(...data.map((d) => d.requests)) })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-600 uppercase", children: "Avg Completion" }), _jsxs("p", { className: "text-2xl font-bold text-gray-900", children: [((data.reduce((sum, d) => sum + d.completions / d.requests, 0) / data.length) * 100).toFixed(1), "%"] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-gray-600 uppercase", children: "Active Users" }), _jsx("p", { className: "text-2xl font-bold text-gray-900", children: Math.max(...data.map((d) => d.users)) })] })] })] }));
}
//# sourceMappingURL=RequestsTrendChart.js.map